name: CI
 
on:
  push:
    branches: ["*"]
 
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"
 
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.10.1
 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"
 
      - name: Test
        run: go test -v -count=1 -race -timeout 5m ./...
 
